CREATE TABLE RECORD (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	data varchar(255) not null
);

create sequence record_sequence start with 1 increment by 1;

insert into RECORD (data) values ('Hello World!');