CREATE TABLE IF NOT EXISTS DEMO (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	data varchar(255) not null
);


create sequence demo_sequence start with 1 increment by 1;

insert into DEMO (data) values ('Hello SDA!');